version: "3.9"
services:

  coin-api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    env_file:
        - .env
    entrypoint: ['yarn', 'start']
    ports:
      - "8080:8080"  
